version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: patrik
      POSTGRES_PASSWORD: super_secret_password

  wallet-app:
    image: patrik_melander_wallet:latest
    container_name: wallet_application
    ports:
      - "8080:8080"
    depends_on:
      - postgres